INSERT INTO quote (text, author, category) VALUES
('The only bad workout is the one that didn''t happen.', 'Unknown', 'motivation'),
('Sweat is just fat crying.', 'Unknown', 'motivation'),
('The last three or four reps is what makes the muscle grow.', 'Arnold Schwarzenegger', 'motivation'),
('Action is the foundational key to all success.', 'Pablo Picasso', 'motivation'),
('Don''t stop when you''re tired. Stop when you''re done.', 'Unknown', 'motivation'),
('Success is usually the culmination of controlling failure.', 'Sylvester Stallone', 'motivation'),
('The pain you feel today will be the strength you feel tomorrow.', 'Unknown', 'motivation'),
('What hurts today makes you stronger tomorrow.', 'Jay Cutler', 'motivation'),
('Strength does not come from physical capacity. It comes from an indomitable will.', 'Mahatma Gandhi', 'motivation'),
('The body achieves what the mind believes.', 'Napoleon Hill', 'motivation'),
('There is no such thing as overtraining, only undereating and undersleeping.', 'Ronnie Coleman', 'motivation'),
('The real workout starts when you want to stop.', 'Unknown', 'motivation'),
('Discipline is doing what needs to be done, even if you don''t want to do it.', 'Unknown', 'motivation'),
('You don''t have to be great to start, but you have to start to be great.', 'Zig Ziglar', 'motivation'),
('The difference between try and triumph is a little umph.', 'Marvin Phillips', 'motivation'),
('Fitness is not about being better than someone else. It''s about being better than you used to be.', 'Khloe Kardashian', 'motivation'),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', 'motivation'),
('Do something today that your future self will thank you for.', 'Sean Patrick Flanery', 'motivation'),
('Your health is an investment, not an expense.', 'Unknown', 'motivation'),
('Don''t limit your challenges. Challenge your limits.', 'Jerry Dunn', 'motivation');
