DROP TABLE IF EXISTS workout_set CASCADE;
DROP TABLE IF EXISTS workout_session CASCADE;
DROP TABLE IF EXISTS routine_exercise CASCADE;
DROP TABLE IF EXISTS routine CASCADE;
DROP TABLE IF EXISTS exercise CASCADE;
DROP TABLE IF EXISTS quote CASCADE;
