// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	TargetMuscle pgtype.Text `json:"target_muscle"`
	Notes        pgtype.Text `json:"notes"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Quote struct {
	ID       uuid.UUID   `json:"id"`
	Text     string      `json:"text"`
	Author   pgtype.Text `json:"author"`
	Category pgtype.Text `json:"category"`
}

type Routine struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type RoutineExercise struct {
	ID         uuid.UUID `json:"id"`
	RoutineID  uuid.UUID `json:"routine_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
	Order      int32     `json:"order"`
}

type WorkoutSession struct {
	ID        uuid.UUID          `json:"id"`
	RoutineID pgtype.UUID        `json:"routine_id"`
	StartedAt time.Time          `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

type WorkoutSet struct {
	ID         uuid.UUID      `json:"id"`
	SessionID  uuid.UUID      `json:"session_id"`
	ExerciseID uuid.UUID      `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	Weight     pgtype.Numeric `json:"weight"`
	Reps       int32          `json:"reps"`
	CreatedAt  time.Time      `json:"created_at"`
}
