// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExercises = `-- name: CountExercises :one
SELECT COUNT(*) FROM exercise
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountExercises(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countExercises, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoutineExercisesByExercise = `-- name: CountRoutineExercisesByExercise :one
SELECT COUNT(*) FROM routine_exercise WHERE exercise_id = $1
`

func (q *Queries) CountRoutineExercisesByExercise(ctx context.Context, exerciseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutineExercisesByExercise, exerciseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkoutSetsByExercise = `-- name: CountWorkoutSetsByExercise :one
SELECT COUNT(*) FROM workout_set WHERE exercise_id = $1
`

func (q *Queries) CountWorkoutSetsByExercise(ctx context.Context, exerciseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkoutSetsByExercise, exerciseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercise (name, target_muscle, notes)
VALUES ($1, $2, $3)
RETURNING id, name, target_muscle, notes, created_at
`

type CreateExerciseParams struct {
	Name         string      `json:"name"`
	TargetMuscle pgtype.Text `json:"target_muscle"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.Name, arg.TargetMuscle, arg.Notes)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetMuscle,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routine (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateRoutine(ctx context.Context, name string) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine, name)
	var i Routine
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createRoutineExercise = `-- name: CreateRoutineExercise :one
INSERT INTO routine_exercise (routine_id, exercise_id, "order")
VALUES ($1, $2, $3)
RETURNING id, routine_id, exercise_id, "order"
`

type CreateRoutineExerciseParams struct {
	RoutineID  uuid.UUID `json:"routine_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
	Order      int32     `json:"order"`
}

func (q *Queries) CreateRoutineExercise(ctx context.Context, arg CreateRoutineExerciseParams) (RoutineExercise, error) {
	row := q.db.QueryRow(ctx, createRoutineExercise, arg.RoutineID, arg.ExerciseID, arg.Order)
	var i RoutineExercise
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.ExerciseID,
		&i.Order,
	)
	return i, err
}

const createWorkoutSession = `-- name: CreateWorkoutSession :one
INSERT INTO workout_session (routine_id, started_at)
VALUES ($1, NOW())
RETURNING id, routine_id, started_at, ended_at
`

func (q *Queries) CreateWorkoutSession(ctx context.Context, routineID pgtype.UUID) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, createWorkoutSession, routineID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createWorkoutSet = `-- name: CreateWorkoutSet :one
INSERT INTO workout_set (session_id, exercise_id, set_number, weight, reps)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, exercise_id, set_number, weight, reps, created_at
`

type CreateWorkoutSetParams struct {
	SessionID  uuid.UUID      `json:"session_id"`
	ExerciseID uuid.UUID      `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	Weight     pgtype.Numeric `json:"weight"`
	Reps       int32          `json:"reps"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRow(ctx, createWorkoutSet,
		arg.SessionID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.Weight,
		arg.Reps,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Weight,
		&i.Reps,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercise WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExercise, id)
	return err
}

const endWorkoutSession = `-- name: EndWorkoutSession :one
UPDATE workout_session
SET ended_at = NOW()
WHERE id = $1
RETURNING id, routine_id, started_at, ended_at
`

func (q *Queries) EndWorkoutSession(ctx context.Context, id uuid.UUID) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, endWorkoutSession, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name, target_muscle, notes, created_at FROM exercise WHERE id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetMuscle,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseByNameAndMuscle = `-- name: GetExerciseByNameAndMuscle :one
SELECT id, name, target_muscle, notes, created_at FROM exercise
WHERE name = $1 AND target_muscle = $2
LIMIT 1
`

type GetExerciseByNameAndMuscleParams struct {
	Name         string      `json:"name"`
	TargetMuscle pgtype.Text `json:"target_muscle"`
}

func (q *Queries) GetExerciseByNameAndMuscle(ctx context.Context, arg GetExerciseByNameAndMuscleParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByNameAndMuscle, arg.Name, arg.TargetMuscle)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetMuscle,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, text, author, category FROM quote WHERE id = $1
`

func (q *Queries) GetQuote(ctx context.Context, id uuid.UUID) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Author,
		&i.Category,
	)
	return i, err
}

const getRandomQuote = `-- name: GetRandomQuote :one
SELECT id, text, author, category FROM quote
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRow(ctx, getRandomQuote)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Author,
		&i.Category,
	)
	return i, err
}

const getRoutine = `-- name: GetRoutine :one
SELECT id, name, created_at FROM routine WHERE id = $1
`

func (q *Queries) GetRoutine(ctx context.Context, id uuid.UUID) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutine, id)
	var i Routine
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getWorkoutSession = `-- name: GetWorkoutSession :one
SELECT id, routine_id, started_at, ended_at FROM workout_session WHERE id = $1
`

func (q *Queries) GetWorkoutSession(ctx context.Context, id uuid.UUID) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getWorkoutSession, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, target_muscle, notes, created_at FROM exercise
ORDER BY name
`

func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetMuscle,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, text, author, category FROM quote
ORDER BY author, text
`

func (q *Queries) ListQuotes(ctx context.Context) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Author,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutineExercises = `-- name: ListRoutineExercises :many
SELECT re.id, re.routine_id, re.exercise_id, re."order", e.name as exercise_name, e.target_muscle
FROM routine_exercise re
JOIN exercise e ON re.exercise_id = e.id
WHERE re.routine_id = $1
ORDER BY re."order"
`

type ListRoutineExercisesRow struct {
	ID           uuid.UUID   `json:"id"`
	RoutineID    uuid.UUID   `json:"routine_id"`
	ExerciseID   uuid.UUID   `json:"exercise_id"`
	Order        int32       `json:"order"`
	ExerciseName string      `json:"exercise_name"`
	TargetMuscle pgtype.Text `json:"target_muscle"`
}

func (q *Queries) ListRoutineExercises(ctx context.Context, routineID uuid.UUID) ([]ListRoutineExercisesRow, error) {
	rows, err := q.db.Query(ctx, listRoutineExercises, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutineExercisesRow{}
	for rows.Next() {
		var i ListRoutineExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.ExerciseID,
			&i.Order,
			&i.ExerciseName,
			&i.TargetMuscle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutines = `-- name: ListRoutines :many
SELECT id, name, created_at FROM routine
ORDER BY created_at DESC
`

func (q *Queries) ListRoutines(ctx context.Context) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Routine{}
	for rows.Next() {
		var i Routine
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSessions = `-- name: ListWorkoutSessions :many
SELECT id, routine_id, started_at, ended_at FROM workout_session
ORDER BY started_at DESC
`

func (q *Queries) ListWorkoutSessions(ctx context.Context) ([]WorkoutSession, error) {
	rows, err := q.db.Query(ctx, listWorkoutSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSession{}
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetsByExercise = `-- name: ListWorkoutSetsByExercise :many
SELECT ws.id, ws.session_id, ws.exercise_id, ws.set_number, ws.weight, ws.reps, ws.created_at, s.started_at as session_started_at
FROM workout_set ws
JOIN workout_session s ON ws.session_id = s.id
WHERE ws.exercise_id = $1
ORDER BY ws.created_at DESC
`

type ListWorkoutSetsByExerciseRow struct {
	ID               uuid.UUID      `json:"id"`
	SessionID        uuid.UUID      `json:"session_id"`
	ExerciseID       uuid.UUID      `json:"exercise_id"`
	SetNumber        int32          `json:"set_number"`
	Weight           pgtype.Numeric `json:"weight"`
	Reps             int32          `json:"reps"`
	CreatedAt        time.Time      `json:"created_at"`
	SessionStartedAt time.Time      `json:"session_started_at"`
}

func (q *Queries) ListWorkoutSetsByExercise(ctx context.Context, exerciseID uuid.UUID) ([]ListWorkoutSetsByExerciseRow, error) {
	rows, err := q.db.Query(ctx, listWorkoutSetsByExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutSetsByExerciseRow{}
	for rows.Next() {
		var i ListWorkoutSetsByExerciseRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Weight,
			&i.Reps,
			&i.CreatedAt,
			&i.SessionStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetsBySession = `-- name: ListWorkoutSetsBySession :many
SELECT ws.id, ws.session_id, ws.exercise_id, ws.set_number, ws.weight, ws.reps, ws.created_at, e.name as exercise_name
FROM workout_set ws
JOIN exercise e ON ws.exercise_id = e.id
WHERE ws.session_id = $1
ORDER BY ws.created_at
`

type ListWorkoutSetsBySessionRow struct {
	ID           uuid.UUID      `json:"id"`
	SessionID    uuid.UUID      `json:"session_id"`
	ExerciseID   uuid.UUID      `json:"exercise_id"`
	SetNumber    int32          `json:"set_number"`
	Weight       pgtype.Numeric `json:"weight"`
	Reps         int32          `json:"reps"`
	CreatedAt    time.Time      `json:"created_at"`
	ExerciseName string         `json:"exercise_name"`
}

func (q *Queries) ListWorkoutSetsBySession(ctx context.Context, sessionID uuid.UUID) ([]ListWorkoutSetsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listWorkoutSetsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutSetsBySessionRow{}
	for rows.Next() {
		var i ListWorkoutSetsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Weight,
			&i.Reps,
			&i.CreatedAt,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const searchExercises = `-- name: SearchExercises :many
SELECT id, name, target_muscle, notes, created_at FROM exercise
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchExercisesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchExercises(ctx context.Context, arg SearchExercisesParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, searchExercises, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetMuscle,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercise
SET name = $2, target_muscle = $3, notes = $4
WHERE id = $1
RETURNING id, name, target_muscle, notes, created_at
`

type UpdateExerciseParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	TargetMuscle pgtype.Text `json:"target_muscle"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExercise,
		arg.ID,
		arg.Name,
		arg.TargetMuscle,
		arg.Notes,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetMuscle,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
